### ISSUE TITLE
Add support for configurable screenshot filename

### ISSUE THREAD

**Issue by gvnabf** [Genetec/azure-devops-extension-publishtestresultscreenshot#4]
**Agent pool:** Private pool
**Agent specification:** macOS
**Context:** Android - codeceptjs-appium
**Test result format:** jUnit (generated by using mocha-junit-reporter, mocha-multi)

**Describe the bug**
Publish test result screenshot task completes but with a warning that says
```
1 tests failed. Will proceed with screenshot upload.
##[warning]All screenshots were missing. 
Task completed. Published 0/1 screenshots
```

**To Reproduce**
1. Add task right after 'Publish Test Results' task
2. Provide organization
3. Provide screenshot folder
4. Run build pipeline
_**Part of yaml being used by the pipeline related to publishing of test results_
```
    ...
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/output'
        publishRunAttachments: true
        # failTaskOnFailedTests: true
      condition: always()
    - task: Genetec.publish-test-result-screenshot.pipeline-extension.PublishTestResultScreenshot@0
      displayName: 'Publish test result screenshot'
      inputs:
        organization: retailshelf
        screenshotFolder: $(System.DefaultWorkingDirectory)/output/
```
**Sample artifact for test results:**
<img width="417" alt="output" src="https://user-images.githubusercontent.com/13460175/97673516-dbe50c00-1ac6-11eb-9cd1-ecd178b88835.png">

**Expected behavior**
It should be able to locate and publish appropriate screenshot for each failed test.
